-d F:\Project\Sipeed\Tang_Primer\Project\show-image\impl\gwsynthesis\dk_video.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst F:\Project\Sipeed\Tang_Primer\Project\show-image\src\dk_video.cst
-cfg F:\Project\Sipeed\Tang_Primer\Project\show-image\impl\pnr\device.cfg
-sdc F:\Project\Sipeed\Tang_Primer\Project\show-image\src\dk_video.sdc
-bit
-tr
-ph
-timing
-correct_hold 1
-route_maxfan 23
