# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Project/FPAG/Vivado_18.3/minecraft_moon/minecraft_moon.srcs/sources_1/ip/texture_rom/texture_rom.xci
# IP: The module: 'texture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project/FPAG/Vivado_18.3/minecraft_moon/minecraft_moon.srcs/sources_1/ip/texture_rom/texture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'texture_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Project/FPAG/Vivado_18.3/minecraft_moon/minecraft_moon.srcs/sources_1/ip/texture_rom/texture_rom.xci
# IP: The module: 'texture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Project/FPAG/Vivado_18.3/minecraft_moon/minecraft_moon.srcs/sources_1/ip/texture_rom/texture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'texture_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
